Local_Theatre/Models/ViewModels/ChangeRoleViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Local_Theatre.Models.ViewModels
{
    //ChangeRoleViewModel class to update from an old to a new Role
    public class ChangeRoleViewModel
    {
        public string UserName { get; set; }
        public string OldRole { get; set; }

        public ICollection<SelectListItem> Roles { get; set; }
        [Required]
        public string Role { get; set; }
    }
}

Local_Theatre/Models/ViewModels/CreateStaffViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Local_Theatre.Models.ViewModels
{
    //CreateStaffViewModel class to create new Staff object
    public class CreateStaffViewModel
    {
        //---------------------------------------
        [Display(Name = "First Name")]
        public string FirstName { get; set; }


        //---------------------------------------
        [Display(Name = "LastName")]
        public string LastName { get; set; }


        //---------------------------------------
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [Display(Name = "Date of Birth")]
        public DateTime DateofBirth { get; set; }


        //---------------------------------------
        [Display(Name = "Address Line 1")]
        public string Addressline1 { get; set; }


        //---------------------------------------
        [Display(Name = "Address Line 2")]
        public string Addressline2 { get; set; }


        //---------------------------------------
        [DataType(DataType.PostalCode)]
        [Display(Name = "Post Codee")]
        public string PostCode { get; set; }


        //---------------------------------------
        public string City { get; set; }


        //---------------------------------------
        [Display(Name = "Email Address")]
        public string Email { get; set; }


        //---------------------------------------
        [Display(Name = "Email Confirmed")]
        public bool EmailConfirmed { get; set; }


        //---------------------------------------
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }


        //---------------------------------------
        [Display(Name = "Phone Confirmed")]
        public bool PhoneConfirmed{ get; set; }


        //---------------------------------------
        public string Password { get; set; }


        //---------------------------------------
        public StaffRole StaffRole { get; set; }

        //---------------------------------------
        public string Role { get; set; }
        public ICollection<SelectListItem> Roles { get; set; }

    }
}

Local_Theatre/Models/ViewModels/EditMemberViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Local_Theatre.Models.ViewModels
{
    //EditMemberViewModel to Edit Member properties
    public class EditMemberViewModel
    {
        //---------------------------------------
        [Display(Name = "First Name")]
        public string FirstName { get; set; }


        //---------------------------------------
        [Display(Name = "LastName")]
        public string LastName { get; set; }


        //---------------------------------------
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{dd/MMM/yyyy}")]
        [Display(Name = "Date of Birth")]
        public DateTime DateofBirth { get; set; }


        //---------------------------------------
        [Display(Name = "Email Address")]
        public string Email { get; set; }


        //---------------------------------------
        [Display(Name = "Email Confirmed")]
        public bool EmailConfirmed { get; set; }


        //---------------------------------------
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }


        //---------------------------------------
        [Display(Name = "Phone Confirmed")]
        public bool PhoneConfirmed { get; set; }

    }
}

Local_Theatre/Models/ViewModels/EditStaffViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Local_Theatre.Models.ViewModels
{
    //EditStaffViewModel to Edit Staff properties
    public class EditStaffViewModel
    {
        //---------------------------------------
        [Display(Name = "First Name")]
        public string FirstName { get; set; }


        //---------------------------------------
        [Display(Name = "LastName")]
        public string LastName { get; set; }


        //---------------------------------------
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{dd/MMM/yyyy}")]
        [Display(Name = "Date of Birth")]
        public DateTime DateofBirth { get; set; }


        //---------------------------------------
        [Display(Name = "Address Line 1")]
        public string Addressline1 { get; set; }


        //---------------------------------------
        [Display(Name = "Address Line 2")]
        public string Addressline2 { get; set; }


        //---------------------------------------
        [DataType(DataType.PostalCode)]
        [Display(Name = "Post Codee")]
        public string PostCode { get; set; }


        //---------------------------------------
        public string City { get; set; }


        //---------------------------------------
        [Display(Name = "Email Address")]
        public string Email { get; set; }


        //---------------------------------------
        [Display(Name = "Email Confirmed")]
        public bool EmailConfirmed { get; set; }


        //---------------------------------------
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }


        //---------------------------------------
        [Display(Name = "Phone Confirmed")]
        public bool PhoneConfirmed { get; set; }
    }
}

Local_Theatre/Controllers/CommentsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Local_Theatre.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Local_Theatre.Controllers
{
    [Authorize]
    public class CommentsController : ApplicationBaseController
    {
        private LocalTheatreDbContext db = new LocalTheatreDbContext();

        // POST: Comments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentId,CommentContext,BlogId")] Comment comment)
        {
            //finding the currently signed in user
            UserManager<User> userManager = new UserManager<User>(new UserStore<User>(db));
            string userId = userManager.FindByEmail(User.Identity.GetUserName()).Id;
            User user = db.Users.Find(userId);
            //fining the blog using BlogId property of comment
            var blog = db.Blogs.Find(comment.BlogId);
            //if user is Mod, SysAmin or blog belogns to user, setting coment to approved, else to unapproved
            if (user.CurrentRole == "Moderator" || user.CurrentRole == "SysAdmin" || blog.UserId == user.Id)
            {
                comment.CommentApproved = true;
            }
            else
            {
                comment.CommentApproved = false;
            }
            //settign the missing values 
            comment.CommentPosted = DateTime.Now;
            comment.UserId = user.Id;
            //if model is valid, adding comment to database and returing to Blog View
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Blog", "Blogs", new { id = comment.BlogId });
            }

            return RedirectToAction("Blog", "Blogs", new { id = comment.BlogId });
        }

        //GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //finding the comment by Id
            Comment comment = db.Comments.Find(id);

            if (comment == null)
            {
                return HttpNotFound();
            }
            //if comment is not null, removing the comment and returnig back to the View
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Blog", "Blogs", new { id = comment.BlogId });
        }


        public ActionResult ApproveComment(int? id) {
            //finding the comment by id, setting the approved to true and returnign back to the Blog View
            Comment comment = db.Comments.Find(id);

            comment.CommentApproved = true;
            db.SaveChanges();

            return RedirectToAction("Blog", "Blogs", new { id = comment.BlogId });
        }

        public ActionResult DisapproveComment(int? id)
        {
            //finding the comment by id, setting the approved to false and returnign back to the Blog View
            Comment comment = db.Comments.Find(id);

            comment.CommentApproved = false;
            db.SaveChanges();

            return RedirectToAction("Blog", "Blogs", new { id = comment.BlogId });
        }

        public ActionResult ApproveAllComments()
        {
            //finding al unapproved comments
            var comments = db.Comments.Where(b => b.CommentApproved == false).ToList();

            //for each comment setting the approved to true and returnign back to the Blog View
            foreach (var item in comments) 
            {
                item.CommentApproved = true;
            }
            db.SaveChanges();

            return RedirectToAction("ModerateComments", "Admin");
        }

        public ActionResult DeteleAllComments()
        {
            //finding al unapproved comments
            var comments = db.Comments.Where(b => b.CommentApproved == false).ToList();
            //for each comment removing the comment and returnign back to the Blog View
            foreach (var item in comments)
            {
                db.Comments.Remove(item);
            }
            db.SaveChanges();

            return RedirectToAction("ModerateComments", "Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Local_Theatre/Views/Admin/ChangeRole.cshtml
@model Local_Theatre.Models.ViewModels.ChangeRoleViewModel
@{
    ViewBag.Title = "ChangeRole";
}

@* Change Password View *@
@* Dropdown menu to choose the role *@

<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Change Role for @Model.UserName</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Role, Model.Roles, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-dark" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "ViewUsers")
        </div>
    </div>
</div>

Local_Theatre/Views/Admin/CreateStaff.cshtml
@model Local_Theatre.Models.ViewModels.CreateStaffViewModel

@{
    ViewBag.Title = "CreateStaff";
}

@* Create new Staff View *@
@* First, Last Names, Date of Birth, Address 1 and 2, Postcode, City and Role *@

<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">

        <h2>Create Staff</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <hr />
            <div class="form">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateofBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateofBirth, "{0:dd/MMM/yyyy}", new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Addressline1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Addressline1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Addressline1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Addressline2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Addressline2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Addressline2, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Role, Model.Roles, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-dark" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "ViewUsers")
        </div>
    </div>
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Local_Theatre/Views/Admin/DatailsCustomer.cshtml
@{
    ViewBag.Title = "DatailsCustomer";
}

@model Local_Theatre.Models.Member

@{
    ViewBag.Title = "DatailsCustomer";
}

@* Details of a member *@

<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h2>@Model.FirstName @Model.LastName</h2>

        <div>
            <h4>Member</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateofBirth)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateofBirth)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RegistereredAt)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RegistereredAt)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EmailConfirmed)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EmailConfirmed)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumberConfirmed)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UserName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MemberStatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MemberStatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Membership)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Membership)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "EditMember", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "ViewUsers")
        </p>
    </div>
</div>

Local_Theatre/Views/Admin/DatailsStaff.cshtml
@model Local_Theatre.Models.Staff

@{
    ViewBag.Title = "DatailsStaff";
}

@* Details of a staff *@

<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h2>@Model.FirstName @Model.LastName</h2>

        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateofBirth)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateofBirth)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RegistereredAt)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RegistereredAt)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EmailConfirmed)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EmailConfirmed)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumberConfirmed)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UserName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Addressline1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Addressline1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Addressline2)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Addressline2)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PostCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PostCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Role)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Role)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "EditStaff", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "ViewUsers")
        </p>
    </div>
</div>

Local_Theatre/Views/Admin/ManageMember.cshtml
@model IPagedList<Local_Theatre.Models.Member>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "ManageMember";
}

@* View will all the memebers, admin can promote or suspend *@

<div class="container-fluid">
    <div class="col-lg-7 col-md-8 mx-auto">

        <br />
        <br />
        <h4>Promote or Suspend Members of <span class="text-primary">Local Theatre</span></h4>
        <table class="table">
            <thead class="thead-dark" style="font-size:20px; font-family:Century Gothic; font-weight:600">
                <tr>
                    <th> @Html.DisplayNameFor(model => model.First().FirstName)</th>
                    <th> @Html.DisplayNameFor(model => model.First().LastName)</th>
                    <th> @Html.DisplayNameFor(model => model.First().UserName)</th>
                    <th> @Html.DisplayNameFor(model => model.First().CurrentRole)</th>
                    <th></th>
                </tr>
            </thead>

            <tbody style="font-size:15px; font-family:Century Gothic; font-weight:300">
                @foreach (var item in Model)
                {
                    <tr>
                        <td> @Html.DisplayFor(modelItem => item.FirstName)</td>
                        <td> @Html.DisplayFor(modelItem => item.LastName)</td>
                        <td> @Html.DisplayFor(modelItem => item.UserName)</td>
                        <td> @Html.DisplayFor(modelItem => item.CurrentRole)</td>
                        <td>
                            @Html.ActionLink("Promote", "PromoteToRole", new { id = item.Id }) |
                            @Html.ActionLink("Suspend", "SuspendMember", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @* pagination *@
        <div class="d-flex justify-content-end" style="font-family:Century Goithic">
            @Html.PagedListPager(Model, page => Url.Action("ManageMember", new { page, Search = Request.QueryString["Search"] }),
            new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
        </div>

    </div>
</div>

Local_Theatre/Views/Admin/ModerateComments.cshtml
@model IPagedList<Local_Theatre.Models.Comment>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "ModerateComments";
}

@* if model is empty, show a message to the user, else show a list of unapproved comments *@

@if (Model.Count() == 0)
{
    <div class="jumbotron jumbotron-fluid">
        <div class="container" style="font-family:Century Gothic">
            <h1 class="display-4">Whops,</h1>
            <p class="lead">We have no comments that need approvel at the moment, please come back later :)</p>
            <a href='@Url.Action("Index", "Home")' class="btn btn-dark">Home Page</a>
        </div>
    </div>
}
else
{
    <div class="container" id="mid">
        <div class="row">
            <div class="col-lg-10 col-md-10 mx-auto">

                <br />
                <div class="d-flex justify-content-center" style="margin-bottom: 5rem">
                    <div class="btn-group btn-group-lg" role="group">
                        <a href='@Url.Action("ApproveAllComments", "Comments")' class="btn btn-light btn-outline-dark">Approve All Commentse</a>
                        <a href='@Url.Action("DeteleAllComments", "Comments")' class="btn btn-light btn-outline-dark">Detele All Comments</a>
                    </div>
                </div>

                @using (Html.BeginForm("ModerateComments", "Admin", FormMethod.Get))
                {
                    <div class="d-flex flex-row" style="font-family:Century Gothic">
                        <div class="input-group">
                            @Html.TextBox("Search", null, new { placeholder = "Search Comment by First or Last Names of a user", @class = "form-control" })
                            <button type="submit" class="fas fa-search" style="background: none; border: none; color: Highlight; font-size:25px; padding: 0; margin:0 30px"> </button>
                        </div>
                    </div>
                }
                <br />

                @foreach (var item in Model)
                {

                    <div class="post-preview">
                        <a>
                            <h5 class="post-subtitle p-2">@item.CommentContext</h5>
                        </a>
                        <div class="d-flex justify-content-end post-meta">
                            <div class="p-2">Posted on: @item.CommentPosted.ToString("dd MMMM yyyy")</div>
                            <div class="p-2">By @item.User.FirstName @item.User.LastName</div>
                        </div>

                        <div class="d-flex justify-content-end post-meta">
                            <div class="px-2"><a href="@Url.Action("ApproveComment", "Comments", new { id = item.CommentId })">Approve</a></div>
                            <div><a href="@Url.Action("Delete", "Comments", new { id = item.CommentId })">Delete</a></div>
                        </div>
                    </div>
                    <hr>
                    <br />
                }

                @* pagination *@
                <div class="d-flex justify-content-end" style="font-family:Century Goithic">
                    @Html.PagedListPager(Model, page => Url.Action("ModerateComments", new { page, Search = Request.QueryString["Search"] }),
                    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
                </div>

            </div>
        </div>
    </div>
}